DROP TABLE "SERVICE";
DROP TABLE "RANK";
DROP TABLE PERSON;

CREATE TABLE "PERSON" (
	"SID" INTEGER PRIMARY KEY,
	"SURNAME" VARCHAR(64) NOT NULL,
	"INITIALS" VARCHAR(32),
	"FORENAMES" VARCHAR(128),
	"BIRTH" DATE,
	"DEATH" DATE,
	"BORNAFTER" DATE,
	"BORNBEFORE" DATE,
	"DIEDAFTER" DATE,
	"DIEDBEFORE" DATE
);

CREATE INDEX PERSON_SURNAME ON PERSON(SURNAME);
CREATE INDEX PERSON_INITIALS ON PERSON(INITIALS);

CREATE TABLE "RANK" (
	"ABBREV" VARCHAR(16) NOT NULL,
	"NAME" VARCHAR(128) NOT NULL,
	"NATO_CODE" VARCHAR(8),
	"ORDINAL" INTEGER,
	CONSTRAINT RANK_PK PRIMARY KEY ("ABBREV")
);

CREATE TABLE "SERVICE" (
	"SID" INTEGER,
	"NUM" VARCHAR(32),
	"RANK" VARCHAR(128),
	"RANK_ABBREV" VARCHAR(16) NOT NULL,
	"RANK_QUALIFIER" CHAR(1),
	"REGIMENT" VARCHAR(128) NOT NULL,
	"UNIT" VARCHAR(128),
	"AFTER" DATE,
	"BEFORE" DATE,
	"RECNO" INT NOT NULL DEFAULT 0,
	CONSTRAINT SERVICE_PK PRIMARY KEY ("SID", "RANK_ABBREV", "REGIMENT", "RECNO"),
	CONSTRAINT SERVICE_FK1 FOREIGN KEY ("SID") REFERENCES PERSON (SID),
	CONSTRAINT SERVICE_FK2 FOREIGN KEY ("RANK_ABBREV") REFERENCES RANK (ABBREV)
);

CREATE INDEX SERVICE_NUM ON SERVICE(NUM);
