-- Linking soldiers to sources
--

DROP TABLE MENTIONS;

CREATE TABLE "MENTIONS" (
	"SID" INTEGER NOT NULL,
	"SOURCE" VARCHAR(128) NOT NULL,
	"SOURCEREF" VARCHAR(128),
	"TYPE" VARCHAR(32)
);

CREATE INDEX MentionSid ON MENTIONS(SID);
