-- Linking soldiers to sources
--

DROP TABLE MENTIONS;

CREATE TABLE "MENTIONS" (
	"SID" INTEGER NOT NULL,
	"SOURCE" VARCHAR(32) NOT NULL,
	"ITEM_REF" VARCHAR(128),
	CONSTRAINT MENTIONS_PK PRIMARY KEY ("SID", "SOURCE"),
	CONSTRAINT MENTIONS_FK1 FOREIGN KEY ("SID") REFERENCES PERSON (SID)
);
