-- Linking soldiers to sources
--

DROP TABLE SOURCES;

CREATE TABLE "SOURCES" (
	"KEY" VARCHAR(32) NOT NULL,
	"LABEL" VARCHAR(128),
	"REF" VARCHAR(128),
	CONSTRAINT SOURCES_PK PRIMARY KEY ("KEY")

);

DROP TABLE MENTIONS;

CREATE TABLE "MENTIONS" (
	"SID" INTEGER NOT NULL,
	"SOURCE" VARCHAR(32) NOT NULL,
	CONSTRAINT MENTIONS_PK PRIMARY KEY ("SID", "SOURCE"),
	CONSTRAINT MENTIONS_FK1 FOREIGN KEY ("SID") REFERENCES PERSON (SID),
	CONSTRAINT MENTIONS_FK2 FOREIGN KEY ("SOURCE") REFERENCES SOURCES ("KEY")
);
